#!/usr/bin/env python

'''
This script will automatically build Turbo Wookie if there is a change to the
frontend.

Be sure that it is in your `.git/hooks` folder with the name of
`post-merge`, and no extension.

You may or may not have to be sure you have permissions to run the script
before it works for you.
'''


from subprocess import call
import os

def find(name, path):
	for root, dirs, files in os.walk(path):
		if name in files:
			return root

def changed(dir):
	#print(call(["git", "diff", "--name-only", "frontend", ""]))
	diff = os.popen("git diff --name-only  HEAD@{1} HEAD " + dir).read()
	return len(diff) != 0

if changed("frontend"):
	os.chdir(find("pubspec.yaml", os.getcwd()))
	print("Running Pub Build")
	call(["pub", "build"])
else:
	print("No Frontend Change")