#!/usr/bin/env python

'''
This script will automatically build Turbo Wookie if there is a change to the
frontend.

Be sure that it is in your `.git/hooks` folder with the name of
`post-merge`, and no extension.

You may or may not have to be sure you have permissions to run the script
before it works for you.
'''


from subprocess import call
import os

# Find the location of a file within a directory.
def find(name, path):
	for root, dirs, files in os.walk(path):
		if name in files:
			return root

# Get the diff of your state vs the state you are pulling.
def diff(dir):
	return os.popen("git diff --name-only  HEAD@{1} HEAD " + dir).read()

# Get the diff
diff = diff("frontend")

# If frontend is in the diff:
if len(diff) != 0:
	# Move to the pubspec's folder.
	os.chdir(find("pubspec.yaml", os.getcwd()))

	# If the pubspec file has been changed, call pub get/upgrade
	if "pubspec.yaml" in diff:
		print("Running Pub Get")
		call(["pub", "get"])
		print("Running Pub Upgrade")
		call(["pub", "upgrade"])

	# Call pub build
	print("Running Pub Build")
	call(["pub", "build"])

else:
	print("No Frontend Change")